{{- if .Values.postgresql.enabled }}
{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scuffinger.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scuffinger.componentLabels" (list . "postgresql") | nindent 4 }}
  annotations:
    {{- include "scuffinger.annotations" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
{{- end }}

