{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scuffinger.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scuffinger.componentLabels" (list . "prometheus") | nindent 4 }}
  annotations:
    {{- include "scuffinger.annotations" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.evaluationInterval }}


    scrape_configs:
      - job_name: "scuffinger-api"
        metrics_path: /metrics
        static_configs:
          - targets: ["{{ include "scuffinger.fullname" . }}:{{ .Values.app.service.port }}"]
            labels:
              instance: "scuffinger-api"
      {{- if .Values.collector.enabled }}
      - job_name: "scuffinger-collector"
        metrics_path: /metrics
        static_configs:
          - targets: ["{{ include "scuffinger.fullname" . }}-collector:{{ .Values.collector.service.port }}"]
            labels:
              instance: "scuffinger-collector"
      {{- end }}
      {{- with .Values.prometheus.extraScrapeConfigs }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}

