{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scuffinger.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scuffinger.componentLabels" (list . "prometheus") | nindent 4 }}
  annotations:
    {{- include "scuffinger.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scuffinger.componentSelectorLabels" (list . "prometheus") | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "scuffinger.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scuffinger.componentLabels" (list . "prometheus") | nindent 4 }}
  annotations:
    {{- include "scuffinger.annotations" . | nindent 4 }}
spec:
  serviceName: {{ include "scuffinger.fullname" . }}-prometheus
  replicas: 1
  selector:
    matchLabels:
      {{- include "scuffinger.componentSelectorLabels" (list . "prometheus") | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/prometheus/configmap.yaml") . | sha256sum }}
        {{- with .Values.prometheus.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "scuffinger.componentSelectorLabels" (list . "prometheus") | nindent 8 }}
        {{- with .Values.prometheus.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      {{- with .Values.prometheus.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prometheus.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.prometheus.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: prometheus
          image: {{ printf "%s:%s" .Values.prometheus.image.repository .Values.prometheus.image.tag }}
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time={{ .Values.prometheus.retention }}"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/consoles"
            - "--web.enable-lifecycle"
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
              readOnly: true
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: {{ include "scuffinger.fullname" . }}-prometheus
  {{- if .Values.prometheus.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.prometheus.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.prometheus.persistence.accessModes | nindent 10 }}
        {{- if .Values.prometheus.persistence.storageClass }}
        storageClassName: {{ .Values.prometheus.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.prometheus.persistence.size }}
  {{- else }}
  volumeClaimTemplates: []
  {{- end }}
{{- end }}

