{{- if and .Values.app.enabled .Values.app.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "scuffinger.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scuffinger.componentLabels" (list . "app") | nindent 4 }}
  annotations:
    {{- include "scuffinger.annotations" . | nindent 4 }}
    {{- with .Values.app.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.app.ingress.className }}
  ingressClassName: {{ .Values.app.ingress.className }}
  {{- end }}
  {{- if .Values.app.ingress.tls }}
  tls:
    {{- range .Values.app.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.app.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "scuffinger.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}

