{{- if .Values.app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scuffinger.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scuffinger.componentLabels" (list . "app") | nindent 4 }}
  annotations:
    {{- include "scuffinger.annotations" . | nindent 4 }}
    {{- with .Values.app.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scuffinger.componentSelectorLabels" (list . "app") | nindent 4 }}
{{- end }}

