{{- if .Values.app.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scuffinger.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scuffinger.componentLabels" (list . "app") | nindent 4 }}
  annotations:
    {{- include "scuffinger.annotations" . | nindent 4 }}
    {{- with .Values.app.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
{{- end }}

