{{- if and .Values.collector.enabled .Values.collector.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "scuffinger.fullname" . }}-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scuffinger.componentLabels" (list . "collector") | nindent 4 }}
  annotations:
    {{- include "scuffinger.annotations" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "scuffinger.fullname" . }}-collector
  minReplicas: {{ .Values.collector.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.collector.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.collector.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.collector.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.collector.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.collector.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}

